# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.ckpt_dir}/${now:%Y-%m-%d_%H-%M-%S} # directory to save the model file
  filename: epoch_{epoch:03d} # checkpoint filename
  monitor: null # name of the logged metric which determines when model is improving
  verbose: False # verbosity mode
  save_last: True # additionally always save an exact copy of the last checkpoint to a file last.ckpt
  save_top_k: -1 # save all checkpoints (set to -1 to save all)
  mode: "min" # "max" means higher metric value is better, can be also "min"
  auto_insert_metric_name: True # when True, the checkpoints filenames will contain the metric name
  save_weights_only: False # if True, then only the model's weights will be saved (saves disk space)
  every_n_train_steps: null # number of training steps between checkpoints
  train_time_interval: null # checkpoints are monitored at the specified time interval
  every_n_epochs: 20 # save checkpoint every 20 epochs
  save_on_train_epoch_end: null # whether to run checkpointing at the end of the training epoch or the end of validation
